-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 10:28:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_usuario` (
  `idtbl_usuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(45) NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtbl_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(45) NOT NULL,
  `conteudo_programatico` VARCHAR(50) NOT NULL,
  `carga_horaria` TIME NOT NULL,
  `valor_mensalidade` FLOAT NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL,
  `status_curso` CHAR NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_professor` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `nome_professor` VARCHAR(45) NOT NULL,
  `imagem_professor` VARCHAR(45) NOT NULL,
  `email_professor` VARCHAR(45) NOT NULL,
  `telefone_professor` VARCHAR(11) NOT NULL,
  `salario_professor` FLOAT NOT NULL,
  `nascimento_professor` DATE NOT NULL,
  `cep_professor` VARCHAR(8) NOT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT NULL DEFAULT CURRENT_TIMESTAMP,
  `status_professor` CHAR NOT NULL,
  PRIMARY KEY (`id_professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `numero_turma` VARCHAR(45) NOT NULL,
  `id_professor` INT NOT NULL,
  `id_curso` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_termino` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_termino` TIME NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT NULL DEFAULT CURRENT_TIMESTAMP,
  `tbl_turmacol` VARCHAR(45) NULL,
  `status_turma` CHAR NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_curso_id_curso_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_professor_id_professor _idx` (`id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_curso_id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`tbl_curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_id_professor `
    FOREIGN KEY (`id_professor`)
    REFERENCES `mydb`.`tbl_professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `cpf_aludo` VARCHAR(45) NOT NULL,
  `nome_aluno` VARCHAR(45) NOT NULL,
  `imagem_aluno` LONGBLOB NOT NULL,
  `nascimento_aluno` DATE NOT NULL,
  `telefone_aluno` VARCHAR(11) NOT NULL,
  `email_aluno` VARCHAR(45) NOT NULL,
  `cep_aluno` VARCHAR(8) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_turma` INT NOT NULL,
  `status_aluno` CHAR BINARY NULL,
  PRIMARY KEY (`id_aluno`),
  INDEX `fk_id_turma_id_tuma _idx` (`id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_id_turma_id_tuma `
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`tbl_turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_financeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_financeiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pagador` INT NULL,
  `valor` FLOAT NOT NULL,
  `id_recebedor` INT NULL,
  `data_cadastro` TIMESTAMP NOT NULL,
  `data_vencimento` TIMESTAMP NOT NULL,
  `tipo_financeiro` CHAR(1) NOT NULL,
  `status` CHAR(1) BINARY NULL DEFAULT 'N',
  `observacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_aluno_id_pagador_idx` (`id_pagador` ASC) VISIBLE,
  INDEX `fk_id_professor_id_recebedor_idx` (`id_recebedor` ASC) VISIBLE,
  CONSTRAINT `fk_id_aluno_id_pagador`
    FOREIGN KEY (`id_pagador`)
    REFERENCES `mydb`.`tbl_aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_professor_id_recebedor`
    FOREIGN KEY (`id_recebedor`)
    REFERENCES `mydb`.`tbl_professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
